### ISSUE TITLE
Wifi does only connect every 2nd time. Issue with espressif?

### ISSUE THREAD

**Issue by pingufreak** [SmittyHalibut/EleksTubeHAX#15]
It seems this is an old issue with espressif, or? Did you have the same issues?

**Comment by SmittyHalibut** [comment]
@pingufreak I have seen my clock not connect to wifi on occasion, it just prints `...` forever. See https://github.com/SmittyHalibut/EleksTubeHAX/issues/4

Is that what you're talking about?  Or is this something else?
