### ISSUE TITLE
What to do for ESP32-S2 Wroom?

### ISSUE THREAD

**Issue by zsoltmar** [SmittyHalibut/EleksTubeHAX#17]
My clock has the newer S2 Wroom chip and I might be missing something but it wouldn't compile for that board. Maybe I'm missing something? I tried uploading the compiled firmware, however on boot the serial output says that it's the wrong bootloader. Cheers!

**Comment by SmittyHalibut** [comment]
What's the compilation error? I don't have that hardware so I can't tell you what would be wrong.

**Comment by SmittyHalibut** [comment]
That was 3mo ago. Have you tried updating your libraries and tried again? Ie: have they added support recently?

`VSPI` not being there sounds like a `#include` is missing.

**Comment by aly-fly** [comment]
Standard ESP32 has two SPI ports VSPI and HSPI. One is used for Flash, other for our TFT displays.
Did not dig further what -S2 chip has.

**Comment by SmittyHalibut** [comment]
Resolving due to lack of response from OP @zsoltmar.

Several folks have added support for new hardware platforms, not sure if your platform is in there.  Might be worth pulling down the recent code and seeing if it works now.
