### ISSUE TITLE
How to use without WPS

### ISSUE THREAD

**Issue by triggad23** [SmittyHalibut/EleksTubeHAX#24]
Hi,

how can I use this without WPS? My Wifi APs don't support WPS.

Greets
Daniel

**Comment by aly-fly** [comment]
Hello, currently only WPS is implemented. No manual WiFi selection.
You can replace the line `wifi.begin();` with `wifi.begin(YOUR_SSID, YOUR_PASSWORD);` and this should work fine for your case.

**Comment by kogeki** [comment]
> Hello, currently only WPS is implemented. No manual WiFi selection. You can replace the line `wifi.begin();` with `wifi.begin(YOUR_SSID, YOUR_PASSWORD);` and this should work fine for your case.

Hello,

Which file should I change? In WiFi_WPS.cpp, there are 2 lines.

**Comment by SmittyHalibut** [comment]
https://github.com/SmittyHalibut/EleksTubeHAX/blob/main/EleksTubeHAX/EleksTubeHAX.ino#L60

**Comment by SmittyHalibut** [comment]
https://github.com/SmittyHalibut/EleksTubeHAX/pull/30 implements this.  Resolving.
