### ISSUE TITLE
Documentation - readme

### ISSUE THREAD

**Issue by Frank-Bemelman** [SmittyHalibut/EleksTubeHAX#27]
In the readme section, regarding use of TFT_eSPI

>>>Edit Arduino\..\libraries\TFT_eSPI\User_Setup.h

...should that not be >>> Edit Arduino\..\libraries\TFT_eSPI\User_Setup_Select.h ?

**Comment by SmittyHalibut** [comment]
Yep, I believe you're correct.  Thanks!

**Comment by SmittyHalibut** [comment]
Merged and pushed. Resolving.  Thank you again Frank! :-)
