### ISSUE TITLE
Back to original firmware

### ISSUE THREAD

**Issue by ducanh1603** [SmittyHalibut/EleksTubeHAX#31]
I’ve use winmerge but it doesn’t work. The notification show : ”1 different”. I need some help my clock BLACK OUT 😓. I would appreciate it if someone could help me. Sorry about my bad-english 😂

**Comment by ducanh1603** [comment]
![314CB853-134B-4466-9EFE-5B0FF7C379BD](https://user-images.githubusercontent.com/55188060/210115322-d8d0780d-737e-489b-9441-a08680c69832.png)

**Comment by ducanh1603** [comment]
My MAC id: 78:21:84:6b:c3:98 
Someone please make a binary file flash for me pls. I tried 20-30 times =((((

**Comment by aly-fly** [comment]
I was not able to get my clock back to working state by changing MAC address. Well it works on first power-up but does not work on a second power cycle. So not useful.
If you didn't save your original flash image, there is a very low chance to get it back into original state.
I suggest you load this EleksTubeHax firmware. it is better than original ;)

**Comment by SmittyHalibut** [comment]
>  I suggest you load this EleksTubeHax firmware. it is better than original ;)

he suggests modestly.  ;-)

@ducanh1603 I'm sorry, but I don't think this is something we'll be able to help you with.  If you run into problems getting the EleksTubeHax firmware loaded, let us know.

Good luck.
