### ISSUE TITLE
Display Dimming only morning hours

### ISSUE THREAD

**Issue by icebreaker-ch** [SmittyHalibut/EleksTubeHAX#32]
Display dimming only in the morning hours, e.g. from 2 to 6 o clock does not work as expected.
I changed the code in the file EleksTubeHAX.ino according to the attached patch file (i had to zip it for uploading):

[EleksTubeHAX.ino.patch.zip](https://github.com/SmittyHalibut/EleksTubeHAX/files/10371672/EleksTubeHAX.ino.patch.zip)

**Comment by SmittyHalibut** [comment]
https://github.com/SmittyHalibut/EleksTubeHAX/pull/33  Even better, I do love pull requests.  :-)

Thank you very much.  Some very minor comments on your PR, with suggestions that, if you accept, you should be able to just push a button, then I'll approve and merge.

**Comment by icebreaker-ch** [comment]
Your changes are ok for me...
