### ISSUE TITLE
Clock face freezing randomly

### ISSUE THREAD

**Issue by bitrot-alpha** [SmittyHalibut/EleksTubeHAX#48]
Sometimes the clock face will freeze for a few seconds. This goes away for a while if I power cycle the clock.

I'm using the Arduino IDE and library versions from the readme.

I have MQTT and Geolocation enabled and set up with my own credentials. I disabled WPS and hardcoded my wifi settings. The clock hardware is the EleksTube board. I checked the CH340 chip and all of the power regulators with a multimeter, everything's running at 3.3V.

**Comment by aly-fly** [comment]
Operations, that take longer are:
- Geolocation (to get updated timezone + DST). This runs every day at 3 at night only. 
- Time server sync. This is every couple of hours. Can be longer with bad network conditions. 
- This is every minute or so. Can be longer with bad network conditions.

**Comment by bitrot-alpha** [comment]
Thanks for quick reply!

I disabled MQTT and the clock doesn't seem to freeze any more. The clock seems to struggle with my wifi connection somewhat (even though my smartphone gets -50 dBm RSSI right next to the clock), sometimes when I power cycle the clock it doesn't successfully connect.

I'll try re-enabling MQTT and setting the publish time to every 5 minutes.
