### ISSUE TITLE
Tip for Linux users having trouble running Arduino IDE 1.8.xx

### ISSUE THREAD

**Issue by bitrot-alpha** [SmittyHalibut/EleksTubeHAX#49]
I'm using Fedora Linux 37 (with GNOME DE), and I was having trouble getting the Arduino IDE to show the dropdown menus at the top.

I googled around and found this Arduino forum post: https://forum.arduino.cc/t/ide-menus-disappeared/692220/2
That post links to this GitHub issue: https://github.com/arduino/Arduino/issues/11150

The gist is that if the dropdown menus aren't showing up, your Java version is too new, or you don't have the required font installed.

I tried running the IDE with Java 17, but it gave some weird error about a "missing splash" and didn't finish starting up, so I switched to Java 11.

What I did to fix it:
* rename the `java` folder inside of the Arduino IDE folder to something else, like `java_bak` or something
* install OpenJDK-11 (Fedora command is `sudo dnf in java-11-openjdk`)
    * the two dependencies that installed with it are `xorg-x11-fonts-Type1` and `ttmkfdir`
* set my system Java to be Java 11: `sudo alternatives --config java`
    * if you run `java -version` it should say "Java 11" now
    * if you don't want your system Java to always be 11, run `alternatives` again and pick a different Java version after you exit Arduino IDE

**Comment by aly-fly** [comment]
Arduino version was deleted. Project was migrated to PlatformIO.
