### ISSUE TITLE
Error on compiling

### ISSUE THREAD

**Issue by roccomaster84** [SmittyHalibut/EleksTubeHAX#53]
Hello everybody
I got an error on compiling the firmware and I dont know what to do. Maybe anybody can help me.
This si the error I got:

_In file included from C:\Users\Danny\Documents\Arduino\libraries\TFT_eSPI\TFT_eSPI.cpp:4595:0:
C:\Users\Danny\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp: In member function 'void TFT_eSPI::begin_touch_read_write()':
C:\Users\Danny\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp:22:34: error: 'spi' was not declared in this scope
     if (locked) {locked = false; spi.beginTransaction(SPISettings(SPI_TOUCH_FREQUENCY, MSBFIRST, SPI_MODE0));}
                                  ^
C:\Users\Danny\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp: In member function 'void TFT_eSPI::end_touch_read_write()':
C:\Users\Danny\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp:37:54: error: 'spi' was not declared in this scope
     if(!inTransaction) {if (!locked) {locked = true; spi.endTransaction();}}
                                                      ^
C:\Users\Danny\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp: In member function 'uint8_t TFT_eSPI::getTouchRaw(uint16_t*, uint16_t*)':
C:\Users\Danny\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp:61:3: error: 'spi' was not declared in this scope
   spi.transfer(0xd0);                    // Start new YP conversion
   ^
C:\Users\Danny\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp: In member function 'uint16_t TFT_eSPI::getTouchRawZ()':
C:\Users\Danny\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp:104:3: error: 'spi' was not declared in this scope
   spi.transfer(0xb0);               // Start new Z1 conversion
   ^
Mehrere Bibliotheken wurden für "WiFi.h" gefunden
 Benutzt: C:\Users\Danny\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi
 Nicht benutzt: C:\Arduino\libraries\WiFi
exit status 1
Fehler beim Kompilieren für das Board ESP32 Dev Module._

And how is possible to erase the SPIFFS Partition to load other clocks? Because Arduino IDE says that the Filesystem is full.

Are there any solutions for this error?

**Comment by tomac01** [comment]
Du musst die v1.0.6 vom esp32 Board installieren. Dann sollte es funktionieren.
