### ISSUE TITLE
Hardware version Gen2

### ISSUE THREAD

**Issue by DarthWeber** [SmittyHalibut/EleksTubeHAX#55]
Hi, is this working with Gen2.1 also or do i need to change something? 

Looks like the pinout changed but i don't know how to get it. The boards now hosts a ESP32-Pico-D4

Thanks,
Tom

**Comment by DarthWeber** [comment]
// Chip Select shift register, to select the display
#define CSSR_DATA_PIN (14)      // 14
#define CSSR_CLOCK_PIN (9)      // 9
#define CSSR_LATCH_PIN (10)     // 10

works with Gen2.1 (ESP32 Pico D4 Chip)

**Comment by aly-fly** [comment]
Added support for this clock in the _pio folder.

**Comment by judge2005** [comment]
> // Chip Select shift register, to select the display #define CSSR_DATA_PIN (14) // 14 #define CSSR_CLOCK_PIN (9) // 9 #define CSSR_LATCH_PIN (10) // 10
> 
> works with Gen2.1 (ESP32 Pico D4 Chip)

Do you have a backup of the original firmware on the chip? I would like to try to get some images from it. The updates from Eleksmaker are not the full image, they only include the code portion which does not have images, I assume they stashed them in spiffs or littlefs or whatever.

**Comment by Martinius79** [comment]
@judge2005 I backed up the orginal firmware and I extracted the pictures from it and they are all already present in the `data - other graphics` folder. 
So I guess nothing to do here anymore, just to finish this topic.

As far as I understand, the original FW image can be set to "your" MAC address with a little manipulation of the bin file.

Bye
Martinius
