### ISSUE TITLE
Numbers are on the side

### ISSUE THREAD

**Issue by tomac01** [SmittyHalibut/EleksTubeHAX#56]
Hi all,

I adapted the USER_DEFINES.h regarding WIFI access and compiled the code.

After the upload, the loading texts and numbers appear on the TFTs lying on their side.

Does anyone know what I'm doing wrong or what I forgot during configuration?

cu

**Comment by aly-fly** [comment]
1. Make sure you have correct version of the libraries installed. Too new version may cause this.
2. Display library has an Orientation property. Change it from 0 to 3 (all possible rotations).

**Comment by tomac01** [comment]
My mistake:
I hadn't commented out the first entry in User_Setup_Select.h, so User_Setup.h was still included.

After I corrected that, it works great!

Thank you!
