### ISSUE TITLE
DS1307RTC library by Michael Margolis is maintained by Paul Stoffregen

### ISSUE THREAD

**Issue by Fastdruid** [SmittyHalibut/EleksTubeHAX#59]
The instructions are explicit to use only the libraries listed however when searching for "DS1307RTC by Michael Margolis (developed on v1.4.1)" in the library manager this isn't found and instead only one by "Paul Stoffregen" is found. 

![image](https://github.com/SmittyHalibut/EleksTubeHAX/assets/51973882/61868549-c83a-42fa-ba6b-52dddb5234a5)

On looking this up however its written by Michael Margolis but maintained by Paul Stoffregen https://www.arduinolibraries.info/libraries/ds1307-rtc

**Comment by Fastdruid** [comment]
Same goes for "Time by Michael Margolis (developed on v1.6.0)"

**Comment by aly-fly** [comment]
Thanks for reporting. It looks like names changed since the instructions were written. 
Please report back if the project builds and works fine, we will update the instructions.

**Comment by aly-fly** [comment]
Added updated lib descriptions in [my fork](https://github.com/aly-fly/EleksTubeHAX). Will be merged here a bit later.
