### ISSUE TITLE
power-button issues

### ISSUE THREAD

**Issue by jont-studioj** [SmittyHalibut/EleksTubeHAX#6]
Accepting that the current button-code / menu-code / display-enable-code might just be a hacky try-out, I thought I better report this anyway...

1) Not sure if it's an issue with my particular h/w but if I click the [power] button to switch the displays off then..
if, before I toggle the displays back "on" again,

- if the second-unit digit changes (likely) then it will not be repainted when the displays are enabled again
- if the second-tens digit changes then it too does not get repainted when the displays are enabled again
in both cases the display remains black/blank

Oddly it does not seem to affect any minutes/hours digits (I left it "running", in the "off" state, overnight).

Nor does invoking the menu (at the left-hand most display), while in display-off mode, have this adverse effect.

A hard-power down/up does resolve it, as does (I think) re-downloading the f/w from the ArduinoIDE.

This issue is at least avoided (and does not become apparent, whatever is causing it) if the following secondary issue is addressed:

2) If in the display-off mode then only the [power] button should be be taken notice of and all others should be ignored... otherwise you can go blindly into the menu system if you fumble with the buttons when you can't see what you are doing.

I made a hack to just skip almost the entire main loop if in display-off mode. Maybe this should be more intelligent (like maybe keep the timekeeping up to date, listen out for other events etc) but this was a simple proff-of-concept hack and the breaking-displays no longer happens.

I am new to Github and really have little idea what I am doing, particularly I do not know the correct/preferred etiquette, nevertheless, I did take a fork - and then made a branch (on my fork) just for this hack. I don't expect you to take it (I am not marked as a contributor - (and that's ok!))

cheers
jont

**Comment by SmittyHalibut** [comment]
Your #1: Correct. As currently written, pressing "Power" to disable displays doesn't actually disable any microcontroller functions.  That's an easy fix.  Pushed.
