### ISSUE TITLE
Where is the prebuilt firmware?

### ISSUE THREAD

**Issue by mattfox27** [SmittyHalibut/EleksTubeHAX#68]
Where can I find pre built firmware?  Is it in the Repo?

**Comment by aly-fly** [comment]
Not done yet. Can start with that, maybe this weekend. Which config you need first?

**Comment by jwm0001** [comment]
Looking got gen2[EleksTubeIPS Gen 2 hardware], i brick it by flashing it with wrong bin file

**Comment by victorvuelma** [comment]
@aly-fly 

What do you think about using GitHub releases to make multiple pre-built available? We can setup a GitHub action to automate the compilation process

**Comment by jwm0001** [comment]
You talking about you creating those per-built. I have no experience in the compile of the software.

**Comment by aly-fly** [comment]
> What do you think about using GitHub releases to make multiple pre-built available? 
That could be a solution.

> We can setup a GitHub action to automate the compilation process
Not sure if this will work, as it is required to build a complete flash image, including partition table, app, NVS section, SPIFFS with image files.. Sure it can be done with build tools, but the proven and simple way is to build and upload everything into actual ESP32 and then dump the .bin file from that.

**Comment by mattfox27** [comment]
I ended up compiling it myself, which was not easy but I figured it out ;)

**Comment by jwm0001** [comment]
thank you for your help. I really appreciate it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aly-fly** [comment]
Done.
You can find files and notes here:
https://github.com/SmittyHalibut/EleksTubeHAX/tree/main/pre-built-firmware

**Comment by jwm0001** [comment]
I saw this morning, takes for your hard work. Will try this after work.
