### ISSUE TITLE
Digit "0" on PunkCyber has defect

### ISSUE THREAD

**Issue by cool2man** [SmittyHalibut/EleksTubeHAX#79]
The digit "0" on my PunkCyber has a defect. I flashed the actual version (3 times). The color difference (more red, more yellow) is only visible on this image, not in reality.

![Zero_Defect](https://github.com/user-attachments/assets/f44c7856-8997-4dbe-94bf-8a671179f16b)

**Comment by aly-fly** [comment]
I saw the same thing also on my clock. It looks like the file got corrupted somehow. Will take a look in the following days.

**Comment by aly-fly** [comment]
Fixed on the latest commit.
