### ISSUE TITLE
[Info] Home Assistant Edition with extensive MQTT support

### ISSUE THREAD

**Issue by gamba69** [SmittyHalibut/EleksTubeHAX#82]
Home Assistant Edition with extensive MQTT features:
-  Device detected as two different lights, main and back
-  Supported on/off, brightness, effects (main and back), color (back)
-  Supported 12/24 hours and blank zeroes settings switches
-  Supported effect's speed change for backlight
-  All options are discoverable via Home Assistant MQTT

https://github.com/gamba69/EleksTubeHAX

**Comment by eku** [comment]
> Home Assistant Edition with extensive MQTT features

Would you like to incorporate the extensions into this project so that the developments do not diverge?

**Comment by aly-fly** [comment]
> Home Assistant Edition with extensive MQTT features:

It would be great to incorporate this, under a new switch, I recommend `#define MQTT_HOMEASSISTANT`.
Please create a Commit.

**Comment by gamba69** [comment]
Done (as PR).
